version: '3.8'

services:
  resume-parser:
    build:
      context: .
      dockerfile: DockerFile
    container_name: resume-parser-api
    ports:
      - "8000:8000"
    environment:
      # Application configuration
      - MAX_FILE_SIZE=10485760  # 10MB in bytes
      - ALLOWED_FILE_TYPES=.pdf,.docx,.doc
      - GOFR_TELEMETRY=false    # Disable telemetry
      
      # GoFr specific environment variables
      - APP_NAME=resume-parser
      - APP_VERSION=1.0.0
      - LOG_LEVEL=INFO
      - HTTP_PORT=8000
      
    volumes:
      # Mount temp directory for file processing
      - temp_files:/tmp
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Network configuration
    networks:
      - resume-parser-network

  # Optional: Add a reverse proxy (nginx) for production
  nginx:
    image: nginx:alpine
    container_name: resume-parser-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - resume-parser
    restart: unless-stopped
    networks:
      - resume-parser-network
    profiles:
      - production  # Only start with --profile production

# Named volumes
volumes:
  temp_files:
    driver: local

# Networks
networks:
  resume-parser-network:
    driver: bridge